# Site settings
title: 
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://betmenholic.github.io/" # the base hostname & protocol for your site

author:
  fullname: betmen
  googleplus: https://plus.google.com/105848793803107180399/
  github: betmenholic
  twitter: betmenholic
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown